sudo: false
language: node_js
node_js:
  - 'iojs'
  - '0.12'
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-slack-command' ]; then cd .. && eval "mv $currentfolder generator-slack-command" && cd generator-slack-command; fi

